source ~/.profile

if which vise 2> /dev/null > /dev/null; then
    export EDITOR=vise
    export VISUAL=vise
fi

PS1="\w\n;: "
. ~/.iterm2_shell_integration.bash

if [[ "$TERM_PROGRAM" == "vscode" ]] ; then
   . "$(code --locate-shell-integration-path bash)"
else
   if which starship 2> /dev/null >/dev/null; then
      eval "$(starship init bash)"
   fi
fi

#if which powerline-go 2> /dev/null >/dev/null; then
#    function _update_ps1() {
#        PS1="$(powerline-go -error $?)"
#    }
#
#    PROMPT_COMMAND="_update_ps1"
#fi

shopt -s checkhash
shopt -s cmdhist
shopt -s histappend
shopt -s histreedit
shopt -s histverify
shopt -s lithist
shopt -s no_empty_cmd_completion

alias less='less -R'

if which brew >/dev/null 2>&1; then
    if [ -f $(brew --prefix)/etc/bash_completion ]; then
        . $(brew --prefix)/etc/bash_completion
    fi
fi

alias wow="git status"
alias such=git
alias very=git
alias please=sudo

if which nvim 2>/dev/null >/dev/null; then
    alias vim=nvim
    alias vi=nvim
elif which vim 2>/dev/null >/dev/null; then
    alias vi=vim
fi

if [ -r ~/.bash_profile.local ]; then 
    . ~/.bash_profile.local
fi

if which `git-machete` 2>/dev/null >/dev/null; then
   eval "$(git machete completion bash)"
fi

if which starship > /dev/null 2>&1; then
   function set_win_title(){
      echo -ne "\033]0; $(basename "$PWD") \007"
   }
   starship_precmd_user_func="set_win_title"
fi
