source ~/.profile

source $(brew --prefix)/share/antigen/antigen.zsh
fpath=($(brew --prefix)/share/zsh-completions $fpath)

antigen use oh-my-zsh

# antigen bundle git
# antigen bundle git-prompt
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle softmoth/zsh-vim-mode
antigen bundle laravel

antigen theme robbyrussell

antigen apply

if which starship 2> /dev/null >/dev/null; then
    source <(starship init zsh --print-full-init)
fi

autoload -U compinit && compinit
fpath=($(brew --prefix)/share/zsh-completions $fpath)

if which awless 2> /dev/null >/dev/null; then
    source <(awless completion zsh)
fi

if which zoxide 2>/dev/null >/dev/null; then
    source <(zoxide init zsh)
fi

#if which powerline-go 2> /dev/null >/dev/null; then
#    function powerline_precmd() {
#        PS1="$(powerline-go -error $? -shell zsh)"
#    }
#
#    function install_powerline_precmd() {
#        for s in "${precmd_functions[@]}"; do
#            if [ "$s" = "powerline_precmd" ]; then
#            return
#            fi
#        done
#        precmd_functions+=(powerline_precmd)
#    }
#
#    if [ "$TERM" != "linux" ]; then
#        install_powerline_precmd
#    fi
#fi

setopt no_share_history
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C $(brew --prefix)/bin/kustomize kustomize

export PATH="$(brew --prefix)/opt/php@7.4/bin:$PATH"
export PATH="$(brew --prefix)/opt/php@7.4/sbin:$PATH"
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
