source ~/.profile

if which brew 2>/dev/null >/dev/null; then
    BREW=yes
fi

if [ -n "$BREW" ]; then
    source $(brew --prefix)/share/antigen/antigen.zsh
    fpath=($(brew --prefix)/share/zsh-completions $fpath)
else
    source /usr/share/zsh-antigen/antigen.zsh
fi

antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle softmoth/zsh-vim-mode@main
antigen bundle laravel
antigen bundle VirtusLab/git-machete completion

antigen theme robbyrussell

antigen apply

zstyle ':completion:*:*' ignored-patterns '*ORIG_HEAD'

autoload -U compinit && compinit

if which starship 2> /dev/null >/dev/null; then
    source <(starship init zsh --print-full-init)
fi

if which awless 2> /dev/null >/dev/null; then
    source <(awless completion zsh)
fi

if which zoxide 2>/dev/null >/dev/null; then
    source <(zoxide init zsh)
fi

#if which powerline-go 2> /dev/null >/dev/null; then
#    function powerline_precmd() {
#        PS1="$(powerline-go -error $? -shell zsh)"
#    }
#
#    function install_powerline_precmd() {
#        for s in "${precmd_functions[@]}"; do
#            if [ "$s" = "powerline_precmd" ]; then
#            return
#            fi
#        done
#        precmd_functions+=(powerline_precmd)
#    }
#
#    if [ "$TERM" != "linux" ]; then
#        install_powerline_precmd
#    fi
#fi

setopt no_share_history
autoload -U +X bashcompinit && bashcompinit

export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

if which himalaya > /dev/null; then
    eval `himalaya completion zsh`
fi

if [ -d /opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/ ]; then
    source "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
    source "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
fi
