tap "homebrew/cask"
tap "mas-cli/tap"
tap "filippo.io/age", "https://filippo.io/age"

cask_args appdir: "~/Applications"

brew "age"
brew "ansible"
brew "antigen"
brew "awscli"
brew "bandwhich"
brew "bash-completion"
brew "bash-git-prompt"
brew "bat"
brew "composer"
brew "crystal"
brew "deno"
brew "elvish"
brew "encfs"
brew "fx"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "gitbatch"
brew "gnupg"
brew "graphviz"
brew "jq"
brew "llvm"
brew "lua"
brew "luajit"
brew "luarocks"
brew "mas"
brew "massren"
brew "mosh"
brew "mosh"
brew "msmtp"
brew "mycli"
brew "navi"
brew "neovim"
brew "ngrep"
brew "node"
brew "nq"
brew "procs"
brew "pwgen"
brew "python"
brew "qemu"
brew "redis"
brew "rust"
brew "rustup-init"
brew "sc-im"
brew "sqlite"
brew "ssh-copy-id"
brew "starship"
brew "terraform"
brew "vis"
brew "watchman"
brew "xhyve"
brew "xz"
brew "zsh-completions"

cask "firefox"

mas "1Password 7", id: 1333542190
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Xcode", id: 497799835
mas "Microsoft To Do", id: 1274495053
