tap "homebrew/cask"
tap "mas-cli/tap"
tap "filippo.io/age", "https://filippo.io/age"

cask_args appdir: "~/Applications"

brew "age"
# brew "amp"
brew "ansible"
brew "antigen"
brew "awscli"
# brew "bandwhich"
brew "bash-completion"
brew "bash-git-prompt"
brew "bat"
brew "composer"
# brew "crystal"
brew "deno"
brew "elvish"
# brew "encfs"
brew "fx"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "gitbatch"
brew "gnupg"
brew "graphviz"
brew "html1"
brew "jc"
brew "jq"
brew "llvm"
brew "lua"
# brew "luajit"
# brew "luarocks"
brew "mas"
brew "massren"
brew "mosh"
brew "mosh"
brew "msmtp"
brew "murex"
brew "mycli"
brew "navi"
brew "neovim"
brew "ngrep"
brew "node"
brew "nq"
brew "procs"
brew "pwgen"
brew "python"
brew "qemu"
brew "qp"
brew "redis"
brew "rustup-init"
brew "sc-im"
brew "sqlite"
brew "ssh-copy-id"
brew "starship"
brew "terraform"
brew "tmux"
brew "tre"
#brew "uutils-coreutils"
brew "vim"
brew "vis"
brew "watchman"
brew "xz"
brew "yq"
brew "zsh-completions"

cask "affinity-photo"
cask "affinity-designer"
cask "discord"
cask "firefox"
cask "zerotier-one"
cask "visual-studio-code"
cask "around"
cask "wezterm"

mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
#mas "Xcode", id: 497799835
mas "Slack", id: 803453959
