#!/usr/bin/env ruby

# from http://errtheblog.com/posts/89-huba-huba

home = File.expand_path('~')

Dir['dotfiles/*'].each do |file|
  target = File.join(home, ".#{File.basename file}")
  File.unlink target rescue Errno::ENOENT
  File.symlink(File.expand_path(file), target)
end
