#!/usr/bin/env ruby

# from http://errtheblog.com/posts/89-huba-huba

home = File.expand_path('~')

Dir['*'].each do |file|
  next if file =~ /install/
  target = File.join(home, ".#{file}")
  `ln -sfn #{File.expand_path file} #{target}`
end

system "cd ~/.vim/bundle/tern_for_vim; npm install"

