return {
    { 'elixir-editors/vim-elixir' },
    { 'haya14busa/vim-edgemotion' },
    { 'stevearc/oil.nvim' },
    { 'tpope/vim-markdown' },
    { 'jceb/vim-orgmode' },
    { 'kylechui/nvim-surround' },
    { 'preservim/vim-pencil' },
    { 'dbmrq/vim-ditto' },
    { 'kana/vim-textobj-user' },
    { 'preservim/vim-textobj-quote' },
    { 'preservim/vim-textobj-sentence' },
    { 'tommcdo/vim-exchange' },
    { 'pangloss/vim-javascript' },
    { 'tpope/vim-commentary' },
    { 'mattn/emmet-vim' },
    { 'challenger-deep-theme/vim',     lazy = false },
    { 'evanleck/vim-svelte' },
    { 'ciaranm/detectindent',          lazy = false },
    { 'leafgarland/typescript-vim' },
    { 'udalov/kotlin-vim' },
    { 'jwalton512/vim-blade' },
    { 'vim-crystal/vim-crystal' },
    { 'nvim-telescope/telescope.nvim' },
};
