GOOSE_MODEL: lfm2-1.2b-mlx-tools
GOOSE_PROVIDER: openai
GOOSE_MODE: smart_approve
OPENAI_BASE_PATH: v1/chat/completions
extensions:
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  jetbrains:
    bundled: true
    display_name: Jetbrains
    enabled: false
    name: jetbrains
    timeout: 300
    type: builtin
  memory:
    bundled: true
    display_name: Memory
    enabled: false
    name: memory
    timeout: 300
    type: builtin
  playwright:
    args:
    - -y
    - '@playwright/mcp@latest'
    bundled: null
    cmd: npx
    description: ''
    enabled: true
    env_keys: []
    envs: {}
    name: playwright
    timeout: 300
    type: stdio
  tutorial:
    bundled: true
    display_name: Tutorial
    enabled: false
    name: tutorial
    timeout: 300
    type: builtin
OPENAI_HOST: http://localhost:1234
