prompt_order = [ "username", "directory", "git_branch", "git_status", "git_state", "git_commit", "package", "nodejs", "rust", "python", "golang", "terraform", "cmd_duration", "jobs", "battery", "line_break", "character", ]

[character]
symbol = ":;"

[git_branch]
symbol = "🌱 "

[git_commit]
only_detached = false
commit_hash_length = 9
